title: "#skopjehacklab"
description: "#SkopjeHacklab website"
baseurl: ""
url: "" # the base hostname & protocol e.g. http://example.com

# Links
facebook: "https://facebook.com/skopjehacklab"
twitter: "https://twitter.com/2cmk"
github: "https://github.com/skopjehacklab"
mailing_list: "https://lists.softver.org.mk/listinfo/ossm-members"
IRC: "https://webchat.freenode.net/?channels=lugola"

permalink: pretty

# Neighbors
neighbors:
  - name: "Prishtina Hackerspace in Prishtina, Kosovo"
    url: "http://www.prishtinahackerspace.org/"
  - name: "Hacklab Belgrade in Belgrade, Serbia"
    url: "https://oosm.org/"
  - name: "OpenLabs Albania in Tirana, Albania"
    url: "https://openlabs.cc/en/"
  - name: "Bonevet Makerspace in Gjakova, Kosovo"
    url: "https://www.bonevet.org/"
  - name: "Init Lab in Sofia, Bulgaria"
    url: "https://initlab.org/"
  - name: "Hackerspace.gr in Athens, Greece"
    url: "https://www.hackerspace.gr"

# NavBar
navigation:
  - title: "Дома"
    url: "/"
  - title: "Приклучи се"
    url: "/members/"
  - title: "Настани"
    url: "/events/"
  - title: "Блог"
    url: "/blog/"
  - title: "Донации"
    url: "/donations/"
  - title: "Вики"
    url: "https://wiki.spodeli.org/"
  - title: "ЧПП"
    url: "/faq/"


# In order for a new FAQ to be rendered
# you need to rebuild the website
faq:
  - title: "Зошто хаклаб?"
    description: "За да научиш нови работи од светот на софтверот и хардверот, да најдеш помош за доразвивање
                на некои од твоите идеи што мислиш дека никогаш нема да ги реализираш, да ти се средат
                проблемите во животот со GNU/Linux дистрибуциите, да јадеш наполитанки додека не пукнеш, да
                дознаеш како да се заштитиш на интернет и да ги научиш правата кои ги поседуваш додека
                сурфаш, слободно да пиеш филтер кафе, да добиеш добри насоки за Gnome Women Outreach
                програмата, да добиеш помош за Google Summer Of Codе и да правиш многу други
                интересни работи. <br> <br>
    
                Идејата е сите кои се заинтересирани за слободен софтвер, GNU/Linux, но и општо
                технологија, компјутери, хакирање (не кракирање), мрежи, сервери, електроника, слободна
                култура и општество, геџети, роботи итн., да може да се соберат за да споделат знаења и
                искуства, да дискутираат и експериментираат."
  - title: "Дали треба да бидам член на КИКА за да го посетувам хаклабот?"
    description: "A1"
  - title: "Како да станам член? Колку кошта чланарината?"
    description: "A2"
  - title: "Не сакам да бидам член, но сакам да му помогнам на хаклабот. Што можам да направам?"
    description: "A3"
  - title: "Би сакал да донирам работи кои не ги користам, што можам да ви донирам?"
    description: "A4"
  - title: "Дали треба да бидам член за да доаѓам на настани или курсеви?"
    description: "A5"
  - title: "Кога е отворен хаклабот?"
    description: "A6"
  - title: "Дали можам да доаѓам во хаклабот иако не сум техничко лице?"
    description: "A7"
  - title: "Кои се бенефитите ако сум член?"
    description: "A8"
  - title: "Како да организирам настан во хаклаб?"
    description: "A9"
  - title: "Колку треба да сум стар за да станам член на хаклабот?"
    description: "A10"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 2
paginate_path: "/blog/:num/"

sass:
  sass_dir: assets/css

collections:
  events:
    output: true
